# a='python'
# print(a.upper())

# print('python'.upper())
# print('PYTHON'.lower())
# print('PROGRAM'.casefold())
# print('Mobile'.isupper())
# print('MOBILE'.isupper())
# print('mobiLe'.islower())
# print('mobile'.islower())
# print('PytHon'.swapcase())
# print('pyTHOn CoDe'.capitalize())
# print('pyTHOn coDe'.title())
# print('Real Me'.istitle())
# print('Real me'.istitle())
print('Python program'.startswith('F'))
print('Python program'.startswith('P'))
# print('Python program'.startswith('Pyt'))
# print('Python program'.endswith('Pyt'))
# print('Python program'.endswith('am'))
# print('Python program'.endswith('gram'))
# print(len('python')) 
# print('python'.find('p'))
# print('python'.find('h'))
# print('python'.find('T'))
